# Generated by Django 6.0.1 on 2026-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
