# Generated by Django 6.0.1 on 2026-01-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summer',
            options={'ordering': ['date']},
        ),
    ]
